/* GeoCeDG
 * Copyright (c) 2026 GeoCeDG contributors
 * SPDX-License-Identifier: EUPL-1.2
 */

package org.geocedg.common.kernel.locus.metric;

/** Stable internal diagnostic codes for metric semantics and lifecycle. */
public enum MetricDiagnosticCode2D {
	EMPTY_DOMAIN,
	ISOLATED_POINT,
	COLLAPSED_IMAGE,
	POSITION_STALE,
	POSITION_OUTSIDE_DOMAIN,
	BRANCH_MISSING,
	PROVIDER_VERSION_MISMATCH,
	EVALUATION_FAILED,
	DIFFERENT_LOCUS,
	DIFFERENT_BRANCH,
	DISCONTINUITY,
	TARGET_NOT_REACHABLE,
	STOPPED_AT_BOUNDARY,
	WRAP_CONVENTION,
	UNSUPPORTED_CAPABILITY,
	NUMERICAL_FAILURE,
	LIMIT_NOT_ESTABLISHED,
	POSITIVE_INFINITY,
	NON_RECTIFIABLE,
	INCOMPLETE_AGGREGATE,
	GAP_PRESERVED,
	P1_FAILURE,
	WORK_BUDGET_EXHAUSTED
}
