/* GeoCeDG
 * Copyright (c) 2026 GeoCeDG contributors
 * SPDX-License-Identifier: EUPL-1.2
 */

package org.geocedg.desktop.export;

import java.io.IOException;
import java.io.InputStream;
import java.util.Locale;
import java.util.Objects;
import java.util.Properties;
import java.util.regex.Pattern;

import org.geogebra.common.GeoGebraConstants;

/** Immutable build-time GeoCeDG repository provenance. */
public final class GeoCeDGBuildProvenance {

	/** State of the sources from which the running Desktop classes were built. */
	public enum RepositoryState {
		/** The recorded commit had no observed worktree changes at build time. */
		CLEAN,
		/** The recorded commit had observed worktree changes at build time. */
		DIRTY,
		/** Build-time repository state could not be established. */
		UNAVAILABLE
	}

	/** Build-time authority used to resolve the repository commit. */
	public enum ResolutionSource {
		/** Explicit Gradle build property. */
		GRADLE_PROPERTY,
		/** GitHub Actions checkout commit. */
		GITHUB_SHA,
		/** Git HEAD resolved by the Gradle build. */
		GIT_HEAD,
		/** No repository commit was available. */
		UNAVAILABLE
	}

	private static final String RESOURCE =
			"/org/geocedg/desktop/export/geocedg-build-provenance.properties";
	private static final Pattern COMMIT = Pattern.compile(
			"(?:[0-9a-f]{40}|[0-9a-f]{64})");
	private static final String UNAVAILABLE = "UNAVAILABLE";

	private final String applicationVersion;
	private final String repositoryCommit;
	private final RepositoryState repositoryState;
	private final ResolutionSource resolutionSource;

	/**
	 * Creates one immutable provenance record.
	 *
	 * @param applicationVersion embedded application version
	 * @param repositoryCommit lowercase hexadecimal commit, or {@code UNAVAILABLE}
	 * @param repositoryState build-time repository state
	 * @param resolutionSource build-time resolution authority
	 */
	public GeoCeDGBuildProvenance(String applicationVersion,
			String repositoryCommit, RepositoryState repositoryState,
			ResolutionSource resolutionSource) {
		this.applicationVersion = requireText(applicationVersion,
				"application version");
		String canonicalCommit = requireText(repositoryCommit,
				"repository commit").toLowerCase(Locale.ROOT);
		this.repositoryState = Objects.requireNonNull(repositoryState);
		this.resolutionSource = Objects.requireNonNull(resolutionSource);
		boolean unavailable = UNAVAILABLE.toLowerCase(Locale.ROOT).equals(
				canonicalCommit);
		if (!unavailable && !COMMIT.matcher(canonicalCommit).matches()) {
			throw new IllegalArgumentException(
					"Repository commit must be a 40- or 64-digit hexadecimal value");
		}
		if (unavailable
				!= (resolutionSource == ResolutionSource.UNAVAILABLE)
				|| unavailable
						&& repositoryState != RepositoryState.UNAVAILABLE) {
			throw new IllegalArgumentException(
					"Repository commit and provenance source must agree");
		}
		this.repositoryCommit = unavailable ? UNAVAILABLE : canonicalCommit;
	}

	/**
	 * Loads the deterministic resource generated by the Desktop Gradle build.
	 * Runtime export never invokes Git.
	 *
	 * @return embedded build provenance
	 */
	public static GeoCeDGBuildProvenance load() {
		Properties properties = new Properties();
		try (InputStream stream = GeoCeDGBuildProvenance.class
				.getResourceAsStream(RESOURCE)) {
			if (stream == null) {
				throw new IllegalStateException(
						"GeoCeDG build provenance resource is missing");
			}
			properties.load(stream);
		} catch (IOException exception) {
			throw new IllegalStateException(
					"Cannot load GeoCeDG build provenance", exception);
		}
		if (!"1".equals(properties.getProperty("schema.version"))) {
			throw new IllegalStateException(
					"Unsupported GeoCeDG build provenance schema");
		}
		try {
			return new GeoCeDGBuildProvenance(GeoGebraConstants.VERSION_STRING,
					properties.getProperty("repository.commit"),
					RepositoryState.valueOf(properties.getProperty(
							"repository.state")),
					ResolutionSource.valueOf(properties.getProperty(
							"resolution.source")));
		} catch (IllegalArgumentException | NullPointerException exception) {
			throw new IllegalStateException(
					"Invalid GeoCeDG build provenance resource", exception);
		}
	}

	public String getApplicationVersion() {
		return applicationVersion;
	}

	public String getRepositoryCommit() {
		return repositoryCommit;
	}

	public RepositoryState getRepositoryState() {
		return repositoryState;
	}

	public ResolutionSource getResolutionSource() {
		return resolutionSource;
	}

	/** @return whether an auditable repository commit is embedded */
	public boolean isEstablished() {
		return !UNAVAILABLE.equals(repositoryCommit);
	}

	private static String requireText(String value, String name) {
		if (value == null || value.trim().isEmpty()) {
			throw new IllegalArgumentException(name + " is required");
		}
		return value;
	}
}
